from models.variable import Variable

variables = [
    Variable(
        name="Velocidade do vento",
        unit="m/s",
        startValue=3.0,
        endValue=25.0,
        weight=1.0,
        description="Velocidade mínima para gerar energia é 3 m/s; acima de 25 m/s a turbina é desligada por segurança.",
    ),
    # Removidas variáveis que não aparecem no fluxograma Mermaid
    Variable(
        name="Temperatura do óleo",
        unit="°C",
        startValue=0.0,
        endValue=120.0,
        weight=0.7,
        description="Óleo superaquecido indica possível falha em rolamentos ou engrenagens.",
    ),
    Variable(
        name="Pressão hidráulica das pás",
        unit="bar",
        startValue=80.0,
        endValue=160.0,
        weight=0.7,
        description="Pressão do sistema hidráulico das pás. Fora do normal pode indicar vazamento ou falha.",
    ),
    Variable(
        name="Torque das pás",
        unit="Nm",
        startValue=1000.0,
        endValue=4000.0,
        weight=0.7,
        description="Torque aplicado nas pás. Fora do padrão pode indicar problema mecânico ou de calibração.",
    ),
    Variable(
        name="Ruído mecânico",
        unit="dB",
        startValue=40.0,
        endValue=80.0,
        weight=0.5,
        description="Ruído excessivo pode indicar desgaste ou falha em componentes.",
    ),
    Variable(
        name="Pressão do óleo lubrificante",
        unit="bar",
        startValue=1.0,
        endValue=5.0,
        weight=0.6,
        description="Pressão do óleo lubrificante. Fora do normal pode indicar vazamento ou problema na bomba.",
    ),
    Variable(
        name="Potência gerada",
        unit="kW",
        startValue=0.0,
        endValue=3000.0,
        weight=1.0,
        description="Potência elétrica gerada pela turbina.",
    ),
    Variable(
        name="Temperatura do rolamento",
        unit="°C",
        startValue=0.0,
        endValue=120.0,
        weight=0.7,
        description="Temperatura dos rolamentos. Alta temperatura pode indicar falha iminente.",
    ),
    Variable(
        name="Temperatura do gearbox",
        unit="°C",
        startValue=0.0,
        endValue=120.0,
        weight=0.7,
        description="Temperatura do redutor (gearbox). Alta temperatura pode indicar problema de lubrificação ou desgaste.",
    ),
    Variable(
        name="Consumo elétrico",
        unit="kW",
        startValue=0.0,
        endValue=500.0,
        weight=0.6,
        description="Consumo elétrico dos sistemas auxiliares da turbina.",
    ),
]
